---
title: "Export appliance"
date: 2015-07-31
output:
  html_document:
    css: ../styles.css
    fig_caption: yes
    toc: yes
    number_sections: yes
  pdf_document:
    toc: yes
---

## Requirements

### VM creation

See one of these:

* IFB_cloud_VM_creation.Rmd 
* virtualbox_VM_creation.Rmd
  
### Software installation

See:

* install_rsat_ubuntu14.04.Rmd
* install_snakemake_workflows.Rmd


# Export appliance from VirtualBox

Once the Virtual Machine is working fine, it can be exported to an appliance.

* In VirtualBox, open *File* -> *Export Appliance ...*


## Virtual machines to export

* Select the VM: reg-genomics-[YYMMDD]
* *Next >*


## Storage Settings

* Save as: reg-genomics-[YYMMDD].ova
* Format: OVF 1.0
*	Write Manifest File: check
* *Next >*

## Appliance Settings

* Name:           reg-genomics-[YYMMDD]	
*	Product:		    Regulatory Genomics Pipeline
*	Product-URL:	  -
*	Vendor:		      Claire Rioualen, Jacques van Helden
*	Version:		    2015-07-31
*	Description:	  Regulatory Genomics Pipeline using Snakemake, installed on an Ubuntu 14.04 Virtual Machine. 
*	License:		    Free of use for academic users, non-commercial and non-military usage. 
* *Export*

Forcément c'est super long vu que j'ai généré 60GB+ de data...
**/!\\** La VM ne devrait pas faire 100GB/50GO RAM !! 
Idéalement, elle ne doit contenir \*que\* le workflow, les rules et les programmes...
Data brutes et résultats doivent être à part dans le HD.


## Split the VM -- optional

**OPTIONAL:** split the VM into smaller files. This can be useful for two purposes.

* To transfer files to a FAT-formatted drive for distribution (FAT cannot hold files >4Gb). Note that the final installation drive will have to support files >4Gb for the server version of the VM.
* To facilitate synchronization between local and remote machines.

```
SPLIT_SIZE=3999m
mkdir -p ${TARGET_DIR}/appliances
time split -b ${SPLIT_SIZE} ${SOURCE_DIR}/rsat-vm-2015-02_${VERSION}.ova ${TARGET_DIR}/appliances/rsat-vm-2015-02_${VERSION}.ova.split${SPLIT_SIZE}_
```

# Export appliance - IFB machine

## TODO



# Utilisation de l'image par un utilisateur lambda 

## Générer une VM en externalisant: 

### datas brutes

### genomes etc

### resultats générés 
    
* use "shared folders"" between VM-on-hd and hd ? [cf](https://www.virtualbox.org/manual/ch04.html#sharedfolders)
or
* Enable USB stuff ? 

* What difference ?

* 2 façons indépendantes de lier l'USB : dans VBox ou dans la VM. Différence ? 

#### USB

* need extpack

```
VBoxManage extpack install ~/Desktop/Oracle_VM_VirtualBox_Extension_Pack-4.3.28-100309.vbox-extpack 
```
(download from [here](http://www.oracle.com/technetwork/server-storage/virtualbox/downloads/index.html#extpack))

* Go to VM setting/USB/check both boxes then add usb device

* Problem: USB device not showing up? [see](http://askubuntu.com/questions/365850/virtualbox-not-seeing-any-usb-devices-in-the-usb-filters-settings)

```
sudo apt-get install dkms #should be installed already ?
sudo apt-get install gnome-system-tools
```
Now launch the application - Users and Groups. If you're using unity you can do this by tapping the Super key and type user then click Users and Groups icon to start up the User Settings.

Click Manage Groups, find vboxusers, click properties, add your own user name and any other desired users to the vboxusers group. Click Ok.

Reboot / login/logout should do the trick.

**Fun fact:** une clé usb n'est plus reconnue par l'hôte tant qu'elle est connectée à la VM (physiquement && dans les paramètres)
Pas forcément gênant pour le HD snakemake ? 

**Fun fact 2:** Coupure de la liaison USB dès que la VM se met en veille ?! Ou alors simple bug. Set mise en veille auto à 1h


Concrètement, lorsque l'utilisateur reçoit son HD, il doit : 

* installer VBox localement
* importer l'image .ova
* connecter le HD à sa VM
* vérifier les chemins (py et json) (mount point identique si user sous linux ?...)
* lancer le snakemake
* prendre garde à ne pas craser les résultats existants (#chemins)

-> possibilité de tout faire sur le HD avec un VBox portable ? Apparemment que sous Windows...

-> Créer *soit* une version OVA téléchargeable, *soit* une version bootable complète...

## Il faut aussi externaliser les calculs éventuels

### qsub

### serveur rsat ? 
    
    
    
    
    
    
