---
title: "Creation of an appliance on the IFB cloud"
author: "Claire Rioualen"
date: "July 30, 2015"
output:
  html_document:
    css: ../styles.css
    fig_caption: yes
  pdf_document:
    toc: yes
---

## Virtual disk creation

Optionnal but recommended? Allows you to store data outside the VM, for instance. When the virtual disk is attached to your VM, you can access the data whenever the instance is running.
The disk has to be attached to the VM when it is being created, thus it has to be created prior to the VM. 
See [link](http://www.france-bioinformatique.fr/?q=fr/gestion-des-donn%C3%A9es) for more details.

1. Click *New vDisk* button.
2. Enter a name and a size (whole number equating to GiB). 

**/?\\** I'm guessing RSAT proper install & use require a good 20Go. Is there a limit imposed by the cloud?

## Appliance creation

Useful documents:

[Utilisation avancée du Cloud IFB](http://www.france-bioinformatique.fr/?q=fr/core/cellule-infrastructure/documentation-cloud)

[Cumulo Numbio worksheet](http://www.france-bioinformatique.fr/sites/default/files/fascicule-ibi3_0.pdf)

1. In order to create a virtual machine on the IFB cloud, you need to have a developper account.
You should also make sure that you registered your ssh public key in your user profile: [see FAQ](http://www.france-bioinformatique.fr/?q=fr/profil-dutilisateur-cloud])

2. Log in on the [IFB cloud](http://cloud.france-bioinformatique.fr). Click on *New Instance* button. 

* Choose the appliance **Ubuntu 14.04 IFB**

    * **/!\\** As of July 2015, there are four options for the Ubuntu base of a new VM:

        * Ubuntu 14.04 IFB
        * Ubuntu 14.04 IFB-10GB
        * Ubuntu 14.04 IFB-X2Go
        * Ubuntu v12.02 (base)

    * For some reason, *Ubuntu 14.04 IFB-10GB* raises an *Internal Server Error* (sent mail to Christophe Blanchet 15/08/05).
    * Seems OK as of 15/08/31.

* Name your instance.
* Check **Create appliance**. 
* Select the disk of your choice (should be created prior to the appliance creation, see prev. section).
* Click *Run*.

3. Refresh the page. Your instance should appear in orange because of the creation mode you selected. You can now click on the **ssh** column to see the ssh parameters. It should look like this:

```
Parameters:
host = 192.54.201.177
port = 22
identifiant = root

Command-line connection:
ssh -A -p 22 root@192.54.201.177

Command-line file transfers:
scp -P 22 ${localfile} root@192.54.201.177:
sftp -oPort=22 root@192.54.201.177
```

<!--- Do it in root or rg settings? -->

4. Export your ssh keys from host machine to appliance. 

```
rsync -ruptvl ~/.ssh root@192.54.201.177:~
```
or
```
rioualen@dell3b31852 ~/.ssh $ scp -r id_rsa.pub  id_rsa root@192.54.201.177:.ssh/
```

5. Connect to the VM using the ssh command in a terminal. 

```
ssh -A -p 22 root@192.54.201.177
```

**/?\\** Or rsync?
Back to the VM:
```
ssh-agent > ~/agent
source ~/agent
ssh-add
```



## Configuration

### Create user account.

Followed procedure [here](https://www.digitalocean.com/community/tutorials/how-to-add-and-delete-users-on-an-ubuntu-14-04-vps).

```
adduser rg
password: reg-genomics
```

Grant sudo privileges to rg:
```
visudo
```
Add line:


Quitting root mode:
```
su - rg
```

### Shell coloring

```
nano ~/.bashrc
```
Fetch following paragraph and uncomment command `force-color`.
```
# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes
```
```
source ~/.bashrc
```


# Then

## Software installation

### RSAT suite  

See *$project_home/doc/install_protocols/install_rsat_ubuntu14.04.Rmd*

### Snakemake workflows

See *$project_home/doc/install_protocols/instal_snakemake_workflows.Rmd*


## VM export / submission 

See *$project_home/doc/install_protocols/export_appliance.Rmd*





