FROM adreeve/python-numpy:latest 

ENV PATH /usr/local/bin:$PATH
ENV HOME /home

RUN apt-get update \
    && apt-get --yes install git ssh rsync graphviz \
    wget zlibc zlib1g-dev unzip zip \
    libncurses5-dev libncursesw5-dev libboost-dev \
    python3-pip 

RUN pip3 install snakemake pyyaml psutil

#    python-software-properties\
#    build-essential \
#    python3-software-properties \
#    software-properties-common \
# libncurses5-dev libncursesw5-dev libboost-dev

#docutils 

## Gene-regulation

WORKDIR $HOME

RUN wget https://github.com/rioualen/gene-regulation/archive/4.0.tar.gz && \
    tar zvxf 4.0.tar.gz && \
    ln -s gene-regulation-4.0 gene-regulation && \
    rm 4.0.tar.gz


#RUN make -f scripts/makefiles/install_tools_and_libs.mk all


## Programs


# bowtie2
RUN wget --no-clobber http://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.2.6/bowtie2-2.2.6-linux-x86_64.zip && \
	unzip bowtie2-2.2.6-linux-x86_64.zip && \
	cp `find bowtie2-2.2.6/ -maxdepth 1 -executable -type f` /usr/local/bin

# fastqc
RUN wget --no-clobber http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip && \
	unzip -o fastqc_v0.11.5.zip && \
	chmod +x FastQC/fastqc && \
	ln -s -f FastQC/fastqc /usr/local/bin/fastqc && \
	rm fastqc_v0.11.5.zip


# samtools
RUN wget --no-clobber http://sourceforge.net/projects/samtools/files/samtools/1.3/samtools-1.3.tar.bz2 && \
	bunzip2 -f samtools-1.3.tar.bz2 && \
	tar xvf samtools-1.3.tar && \
	cd samtools-1.3 && \
	make  && \
	sudo make install

# bedtools
RUN wget --no-clobber https://github.com/arq5x/bedtools2/releases/download/v2.24.0/bedtools-2.24.0.tar.gz && \
	tar xvfz bedtools-2.24.0.tar.gz && \
	cd bedtools2 && \
	make && \
	sudo make install


# macs2
RUN sudo pip install MACS2


# homer
RUN wget -nc "http://homer.salk.edu/homer/configureHomer.pl" && \
	perl configureHomer.pl -install homer #&& \
#	cp bin/* /usr/local/bin



RUN pip3 install -U pandas

#RUN echo export SHELL=/bin/bash >> /root/.bashrc
#RUN echo export PATH=$PATH:/root/bin >> /root/.bashrc


MAINTAINER Claire Rioualen <claire.rioualen@inserm.fr> 





#docker pull docker-registry.genouest.org/bioconda/snakemake
#docker pull docker-registry.genouest.org/bioconda/graphviz
#docker pull docker-registry.genouest.org/bioconda/fastqc
#docker pull docker-registry.genouest.org/bioconda/bedtools
#docker pull docker-registry.genouest.org/bioconda/samtools
#docker pull docker-registry.genouest.org/bioconda/bowtie2
#docker pull docker-registry.genouest.org/bioconda/macs2
#docker pull docker-registry.genouest.org/bioconda/homer



